from google import genai
from google.genai import types
from tools.weather_tool import get_weather_tool
from tools.calendar_tool import get_calendar_events

def run_fashion_agent(
        user_prompt: str,
        image_data: dict,
        client: genai.Client
    ) -> str:
    """
    Core agentic reasoning loop for AI Fashion Stylist.
    Uses:
    - Vision data (already extracted)
    - Weather tool
    - Calendar tool
    - Gemini 3 agent reasoning with tool calls
    """

    # System instruction (agent brain) 
    system_instruction = (
        "You are an expert AI Fashion Stylist.\n\n"
        "You MUST base your final recommendation on:\n"
        "1. Vision analysis of the user's clothing\n"
        "2. Current weather conditions\n"
        "3. The user's calendar events\n\n"
        "RULES:\n"
        "- ALWAYS check weather and calendar before answering\n"
        "- If a formal meeting exists, prioritize professional outfits\n"
        "- Be concise, stylish, and explain your reasoning clearly"
    )

    # Tool declarations
    tools = [
        types.Tool(
            function_declarations=[
                types.FunctionDeclaration(
                    name="get_weather_tool",
                    description="Get real-time weather for a city",
                    parameters={
                        "type": "object",
                        "properties": {
                            "city": {
                                "type": "string",
                                "description": "City name"
                            }
                        },
                        "required": ["city"]
                    }
                ),
                types.FunctionDeclaration(
                    name="get_calendar_events",
                    description="Get the user's upcoming calendar events",
                    parameters={
                        "type": "object",
                        "properties": {}
                    }
                )
            ]
        )
    ] 

    # Initial user message
    messages = [
        types.Content(
            role="user",
            parts=[
                types.Part.from_text(
                    f"Vision Data: {image_data}\nUser Request: {user_prompt}"
                )   
            ]
        )  
    ]

    # Agentic loop
    for _ in range(5): # safety limit
        response = client.models.generate_content(
            model="gemini-3-pro-preview",
            contents=messages,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                tools=tools,
                thinking_config=types.ThinkingConfig(
                    thinking_level=types.ThinkingLevel.HIGH
                )
            )
        )

        if not response.candidates:
            return "No response generated by the AI."
        
        model_content = response.candidates[0].content
        # Preserve thought signature automatically
        messages.append(model_content)

        # Tool call check
        tool_calls = [
            part.function_call
            for part in model_content.parts
            if part.function_call
        ]

        # Final answer
        if not tool_calls:
            final_text = "".join(
                part.text for part in model_content.parts if part.text
            )
            return final_text or "No final recommendation generated."

        # Execute tools
        tool_parts = []
        for fc in tool_calls:
            if fc.name == "get_weather_tool":
                result = get_weather_tool(**fc.args)
            elif fc.name == "get_calendar_events":
                result = get_calendar_events()
            else:
                result = {"error": "Unknown tool"}

            tool_parts.append(
                types.Part.from_function_response(
                    name=fc.name,
                    response=result
                )
            )

        # Send tool results back to Gemini
        messages.append(
            types.Content(role="tool", parts=tool_parts)
        )

    return "Agent exceeded maximum reasoning steps"